// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tarqeem/ims/ent/comment"
	"github.com/tarqeem/ims/ent/file"
	"github.com/tarqeem/ims/ent/issue"
	"github.com/tarqeem/ims/ent/project"
)

// IssueCreate is the builder for creating a Issue entity.
type IssueCreate struct {
	config
	mutation *IssueMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (ic *IssueCreate) SetTitle(s string) *IssueCreate {
	ic.mutation.SetTitle(s)
	return ic
}

// SetDescription sets the "description" field.
func (ic *IssueCreate) SetDescription(s string) *IssueCreate {
	ic.mutation.SetDescription(s)
	return ic
}

// SetCreator sets the "Creator" field.
func (ic *IssueCreate) SetCreator(s string) *IssueCreate {
	ic.mutation.SetCreator(s)
	return ic
}

// SetNillableCreator sets the "Creator" field if the given value is not nil.
func (ic *IssueCreate) SetNillableCreator(s *string) *IssueCreate {
	if s != nil {
		ic.SetCreator(*s)
	}
	return ic
}

// SetStatus sets the "status" field.
func (ic *IssueCreate) SetStatus(i issue.Status) *IssueCreate {
	ic.mutation.SetStatus(i)
	return ic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ic *IssueCreate) SetNillableStatus(i *issue.Status) *IssueCreate {
	if i != nil {
		ic.SetStatus(*i)
	}
	return ic
}

// SetDate sets the "date" field.
func (ic *IssueCreate) SetDate(s string) *IssueCreate {
	ic.mutation.SetDate(s)
	return ic
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ic *IssueCreate) SetNillableDate(s *string) *IssueCreate {
	if s != nil {
		ic.SetDate(*s)
	}
	return ic
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (ic *IssueCreate) SetProjectID(id int) *IssueCreate {
	ic.mutation.SetProjectID(id)
	return ic
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (ic *IssueCreate) SetNillableProjectID(id *int) *IssueCreate {
	if id != nil {
		ic = ic.SetProjectID(*id)
	}
	return ic
}

// SetProject sets the "project" edge to the Project entity.
func (ic *IssueCreate) SetProject(p *Project) *IssueCreate {
	return ic.SetProjectID(p.ID)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (ic *IssueCreate) AddCommentIDs(ids ...int) *IssueCreate {
	ic.mutation.AddCommentIDs(ids...)
	return ic
}

// AddComments adds the "comments" edges to the Comment entity.
func (ic *IssueCreate) AddComments(c ...*Comment) *IssueCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ic.AddCommentIDs(ids...)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (ic *IssueCreate) AddFileIDs(ids ...int) *IssueCreate {
	ic.mutation.AddFileIDs(ids...)
	return ic
}

// AddFiles adds the "files" edges to the File entity.
func (ic *IssueCreate) AddFiles(f ...*File) *IssueCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return ic.AddFileIDs(ids...)
}

// Mutation returns the IssueMutation object of the builder.
func (ic *IssueCreate) Mutation() *IssueMutation {
	return ic.mutation
}

// Save creates the Issue in the database.
func (ic *IssueCreate) Save(ctx context.Context) (*Issue, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IssueCreate) SaveX(ctx context.Context) *Issue {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IssueCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IssueCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *IssueCreate) defaults() {
	if _, ok := ic.mutation.Creator(); !ok {
		v := issue.DefaultCreator
		ic.mutation.SetCreator(v)
	}
	if _, ok := ic.mutation.Status(); !ok {
		v := issue.DefaultStatus
		ic.mutation.SetStatus(v)
	}
	if _, ok := ic.mutation.Date(); !ok {
		v := issue.DefaultDate
		ic.mutation.SetDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IssueCreate) check() error {
	if _, ok := ic.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Issue.title"`)}
	}
	if _, ok := ic.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Issue.description"`)}
	}
	if _, ok := ic.mutation.Creator(); !ok {
		return &ValidationError{Name: "Creator", err: errors.New(`ent: missing required field "Issue.Creator"`)}
	}
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Issue.status"`)}
	}
	if v, ok := ic.mutation.Status(); ok {
		if err := issue.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Issue.status": %w`, err)}
		}
	}
	if _, ok := ic.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Issue.date"`)}
	}
	return nil
}

func (ic *IssueCreate) sqlSave(ctx context.Context) (*Issue, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *IssueCreate) createSpec() (*Issue, *sqlgraph.CreateSpec) {
	var (
		_node = &Issue{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(issue.Table, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt))
	)
	if value, ok := ic.mutation.Title(); ok {
		_spec.SetField(issue.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ic.mutation.Description(); ok {
		_spec.SetField(issue.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ic.mutation.Creator(); ok {
		_spec.SetField(issue.FieldCreator, field.TypeString, value)
		_node.Creator = value
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(issue.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ic.mutation.Date(); ok {
		_spec.SetField(issue.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if nodes := ic.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.ProjectTable,
			Columns: []string{issue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_issues = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: issue.CommentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.FilesTable,
			Columns: issue.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IssueCreateBulk is the builder for creating many Issue entities in bulk.
type IssueCreateBulk struct {
	config
	err      error
	builders []*IssueCreate
}

// Save creates the Issue entities in the database.
func (icb *IssueCreateBulk) Save(ctx context.Context) ([]*Issue, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Issue, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IssueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IssueCreateBulk) SaveX(ctx context.Context) []*Issue {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IssueCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IssueCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
