// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tarqeem/ims/ent/project"
	"github.com/tarqeem/ims/ent/user"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *ProjectCreate) SetName(s string) *ProjectCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetOwner sets the "owner" field.
func (pc *ProjectCreate) SetOwner(s string) *ProjectCreate {
	pc.mutation.SetOwner(s)
	return pc
}

// SetLocation sets the "location" field.
func (pc *ProjectCreate) SetLocation(s string) *ProjectCreate {
	pc.mutation.SetLocation(s)
	return pc
}

// SetType sets the "type" field.
func (pc *ProjectCreate) SetType(s string) *ProjectCreate {
	pc.mutation.SetType(s)
	return pc
}

// SetProjectNature sets the "Project_nature" field.
func (pc *ProjectCreate) SetProjectNature(pn project.ProjectNature) *ProjectCreate {
	pc.mutation.SetProjectNature(pn)
	return pc
}

// SetTopLevelPackagesNumber sets the "top_level_packages_number" field.
func (pc *ProjectCreate) SetTopLevelPackagesNumber(i int) *ProjectCreate {
	pc.mutation.SetTopLevelPackagesNumber(i)
	return pc
}

// SetJointVentureNumber sets the "joint_venture_number" field.
func (pc *ProjectCreate) SetJointVentureNumber(i int) *ProjectCreate {
	pc.mutation.SetJointVentureNumber(i)
	return pc
}

// SetExecutionLocation sets the "execution_location" field.
func (pc *ProjectCreate) SetExecutionLocation(s string) *ProjectCreate {
	pc.mutation.SetExecutionLocation(s)
	return pc
}

// SetInvolvedStockholders sets the "involved_stockholders" field.
func (pc *ProjectCreate) SetInvolvedStockholders(i int) *ProjectCreate {
	pc.mutation.SetInvolvedStockholders(i)
	return pc
}

// SetDollarValue sets the "dollar_value" field.
func (pc *ProjectCreate) SetDollarValue(i int) *ProjectCreate {
	pc.mutation.SetDollarValue(i)
	return pc
}

// SetStage sets the "stage" field.
func (pc *ProjectCreate) SetStage(s string) *ProjectCreate {
	pc.mutation.SetStage(s)
	return pc
}

// SetDeliveryStratigies sets the "delivery_stratigies" field.
func (pc *ProjectCreate) SetDeliveryStratigies(s string) *ProjectCreate {
	pc.mutation.SetDeliveryStratigies(s)
	return pc
}

// SetContractingStratigies sets the "contracting_stratigies" field.
func (pc *ProjectCreate) SetContractingStratigies(s string) *ProjectCreate {
	pc.mutation.SetContractingStratigies(s)
	return pc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pc *ProjectCreate) SetUserID(id int) *ProjectCreate {
	pc.mutation.SetUserID(id)
	return pc
}

// SetUser sets the "user" edge to the User entity.
func (pc *ProjectCreate) SetUser(u *User) *ProjectCreate {
	return pc.SetUserID(u.ID)
}

// Mutation returns the ProjectMutation object of the builder.
func (pc *ProjectCreate) Mutation() *ProjectMutation {
	return pc.mutation
}

// Save creates the Project in the database.
func (pc *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProjectCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProjectCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProjectCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Project.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "Project.owner"`)}
	}
	if v, ok := pc.mutation.Owner(); ok {
		if err := project.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Project.owner": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Project.location"`)}
	}
	if v, ok := pc.mutation.Location(); ok {
		if err := project.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Project.location": %w`, err)}
		}
	}
	if _, ok := pc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Project.type"`)}
	}
	if v, ok := pc.mutation.GetType(); ok {
		if err := project.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Project.type": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ProjectNature(); !ok {
		return &ValidationError{Name: "Project_nature", err: errors.New(`ent: missing required field "Project.Project_nature"`)}
	}
	if v, ok := pc.mutation.ProjectNature(); ok {
		if err := project.ProjectNatureValidator(v); err != nil {
			return &ValidationError{Name: "Project_nature", err: fmt.Errorf(`ent: validator failed for field "Project.Project_nature": %w`, err)}
		}
	}
	if _, ok := pc.mutation.TopLevelPackagesNumber(); !ok {
		return &ValidationError{Name: "top_level_packages_number", err: errors.New(`ent: missing required field "Project.top_level_packages_number"`)}
	}
	if v, ok := pc.mutation.TopLevelPackagesNumber(); ok {
		if err := project.TopLevelPackagesNumberValidator(v); err != nil {
			return &ValidationError{Name: "top_level_packages_number", err: fmt.Errorf(`ent: validator failed for field "Project.top_level_packages_number": %w`, err)}
		}
	}
	if _, ok := pc.mutation.JointVentureNumber(); !ok {
		return &ValidationError{Name: "joint_venture_number", err: errors.New(`ent: missing required field "Project.joint_venture_number"`)}
	}
	if v, ok := pc.mutation.JointVentureNumber(); ok {
		if err := project.JointVentureNumberValidator(v); err != nil {
			return &ValidationError{Name: "joint_venture_number", err: fmt.Errorf(`ent: validator failed for field "Project.joint_venture_number": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ExecutionLocation(); !ok {
		return &ValidationError{Name: "execution_location", err: errors.New(`ent: missing required field "Project.execution_location"`)}
	}
	if v, ok := pc.mutation.ExecutionLocation(); ok {
		if err := project.ExecutionLocationValidator(v); err != nil {
			return &ValidationError{Name: "execution_location", err: fmt.Errorf(`ent: validator failed for field "Project.execution_location": %w`, err)}
		}
	}
	if _, ok := pc.mutation.InvolvedStockholders(); !ok {
		return &ValidationError{Name: "involved_stockholders", err: errors.New(`ent: missing required field "Project.involved_stockholders"`)}
	}
	if v, ok := pc.mutation.InvolvedStockholders(); ok {
		if err := project.InvolvedStockholdersValidator(v); err != nil {
			return &ValidationError{Name: "involved_stockholders", err: fmt.Errorf(`ent: validator failed for field "Project.involved_stockholders": %w`, err)}
		}
	}
	if _, ok := pc.mutation.DollarValue(); !ok {
		return &ValidationError{Name: "dollar_value", err: errors.New(`ent: missing required field "Project.dollar_value"`)}
	}
	if v, ok := pc.mutation.DollarValue(); ok {
		if err := project.DollarValueValidator(v); err != nil {
			return &ValidationError{Name: "dollar_value", err: fmt.Errorf(`ent: validator failed for field "Project.dollar_value": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "Project.stage"`)}
	}
	if v, ok := pc.mutation.Stage(); ok {
		if err := project.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Project.stage": %w`, err)}
		}
	}
	if _, ok := pc.mutation.DeliveryStratigies(); !ok {
		return &ValidationError{Name: "delivery_stratigies", err: errors.New(`ent: missing required field "Project.delivery_stratigies"`)}
	}
	if v, ok := pc.mutation.DeliveryStratigies(); ok {
		if err := project.DeliveryStratigiesValidator(v); err != nil {
			return &ValidationError{Name: "delivery_stratigies", err: fmt.Errorf(`ent: validator failed for field "Project.delivery_stratigies": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ContractingStratigies(); !ok {
		return &ValidationError{Name: "contracting_stratigies", err: errors.New(`ent: missing required field "Project.contracting_stratigies"`)}
	}
	if v, ok := pc.mutation.ContractingStratigies(); ok {
		if err := project.ContractingStratigiesValidator(v); err != nil {
			return &ValidationError{Name: "contracting_stratigies", err: fmt.Errorf(`ent: validator failed for field "Project.contracting_stratigies": %w`, err)}
		}
	}
	if _, ok := pc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Project.user"`)}
	}
	return nil
}

func (pc *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Owner(); ok {
		_spec.SetField(project.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := pc.mutation.Location(); ok {
		_spec.SetField(project.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := pc.mutation.GetType(); ok {
		_spec.SetField(project.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := pc.mutation.ProjectNature(); ok {
		_spec.SetField(project.FieldProjectNature, field.TypeEnum, value)
		_node.ProjectNature = value
	}
	if value, ok := pc.mutation.TopLevelPackagesNumber(); ok {
		_spec.SetField(project.FieldTopLevelPackagesNumber, field.TypeInt, value)
		_node.TopLevelPackagesNumber = value
	}
	if value, ok := pc.mutation.JointVentureNumber(); ok {
		_spec.SetField(project.FieldJointVentureNumber, field.TypeInt, value)
		_node.JointVentureNumber = value
	}
	if value, ok := pc.mutation.ExecutionLocation(); ok {
		_spec.SetField(project.FieldExecutionLocation, field.TypeString, value)
		_node.ExecutionLocation = value
	}
	if value, ok := pc.mutation.InvolvedStockholders(); ok {
		_spec.SetField(project.FieldInvolvedStockholders, field.TypeInt, value)
		_node.InvolvedStockholders = value
	}
	if value, ok := pc.mutation.DollarValue(); ok {
		_spec.SetField(project.FieldDollarValue, field.TypeInt, value)
		_node.DollarValue = value
	}
	if value, ok := pc.mutation.Stage(); ok {
		_spec.SetField(project.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := pc.mutation.DeliveryStratigies(); ok {
		_spec.SetField(project.FieldDeliveryStratigies, field.TypeString, value)
		_node.DeliveryStratigies = value
	}
	if value, ok := pc.mutation.ContractingStratigies(); ok {
		_spec.SetField(project.FieldContractingStratigies, field.TypeString, value)
		_node.ContractingStratigies = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.UserTable,
			Columns: []string{project.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_projects = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (pcb *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Project, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
