// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Discipline is the predicate function for discipline builders.
type Discipline func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
